### PR TITLE
[Fix] Enable verification of function executions with multiple imports

### LINKED ISSUE #851: [Bug] `verifyFunctionExecution` throws when input program has imports
## 🐛 Bug Report

`verifyFunctionExecution` throws an error when input program has imports.

### Reasons
`verifyFunctionExecution` is missing an `imports` optional argument.

### PR DESCRIPTION
**Pull request by iamalwaysuncomfortable**
## Motivation

This PR adds the ability to manually verify function executions with multiple imports.

## Test Plan

* Unit tests to test the new functionality are included.

### CODE REVIEW

File: wasm/src/programs/execution.rs [hunk 1]
```diff
@@ -92,49 +93,74 @@ impl Deref for Execution {
...
-    #[wasm_bindgen_test]
-    fn test_execution_verification() {
-        let execution = Execution::from_string(EXECUTION).unwrap();
-        let verifying_key_bytes = crate::types::native::parameters::TransferPublicVerifier::load_bytes().unwrap();
-        let verifying_key = VerifyingKey::from_bytes(&verifying_key_bytes).unwrap();
-        assert!(
-            verify_function_execution(&execution, &verifying_key, &Program::get_credits_program(), "transfer_public")
-                .unwrap()
-        );
-    }
```
Comment (iamalwaysuncomfortable) [inline wasm/src/programs/execution.rs:139]: This doesn't work in the context of the texts because they can't initialize the `XmlHttpRequest` polyfill needed to download the parameters needed to prove this function. Tests regarding this function need to be done on the JS side.

**Review by alexpitsikoulis — APPROVED** [review]
lgtm!

**Review by jaketarnow — APPROVED** [review]
LGTM

File: sdk/src/program-manager.ts [hunk 2]
```diff
@@ -1914,12 +1914,38 @@ class ProgramManager {
...
+     * /// Construct the imports and verifying keys
+     * const imports = { "add_it_up.aleo": program_import };
+     * const importedVerifyingKeys = { "add_it_up.aleo": [["add_it", "verifyingKey1..."]] };
+     *
+     * /// Verify the execution.
+     * const isValid = programManager.verifyExecution(executionResponse, imports, importedVerifyingKeys);
+     * assert(isValid);
      */
-    verifyExecution(executionResponse: ExecutionResponse): boolean {
+    verifyExecution(executionResponse: ExecutionResponse, imports?: ImportedPrograms, importedVerifyingKeys?: ImportedVerifyingKeys): boolean {
```
Comment (Pauan) [inline sdk/src/program-manager.ts:1986]: At some point we really do need to use an object for the options instead of multiple arguments, but that should be done in a separate PR.

File: sdk/tests/program-manager.test.ts [hunk 3]
```diff
@@ -7,11 +8,13 @@ import {
...
     stateRoot
 } from "./data/account-data";
-import { Account, ExecutionResponse, OfflineQuery, ProgramManager, RecordPlaintext } from "../src/node";
+import { IMPORT_1, IMPORT_2, MINT_VERIFYING_KEY, PROGRAM, SPEND_VERIFYING_KEY, SPIN_VERIFYING_KEY } from "./data/program";
+import { expect } from "chai";
 
 describe('Program Manager', () => {
     const programManager = new ProgramManager("https://api.explorer.provable.com/v1", undefined, undefined);
     programManager.setAccount(new Account({privateKey: statePathRecordOwnerPrivateKey}));
+    const network = (<AleoNetworkClient>programManager.networkClient).host  === "https://api.explorer.provable.com/v1/testnet" ? "testnet" : "mainnet";
```
Comment (Pauan) [inline sdk/tests/program-manager.test.ts]: Should we add a property to make it easier to detect which network is being used?

File: wasm/src/programs/execution.rs [hunk 4]
```diff
@@ -92,49 +100,84 @@ impl Deref for Execution {
...
     let mut process = ProcessNative::load_web().map_err(|e| e.to_string())?;
+    let program_native = ProgramNative::from(program);
+
+    // First resolve the program's imports.
+    ProgramManager::resolve_imports(&mut process, program, imports)?;
+
+    // Secondly, get the verifying keys and insert them into the process object.
+    if let Some(imported_verifying_keys) = imported_verifying_keys {
+        // Go through the imports and get the program IDs.
+        let program_ids = Object::entries(&imported_verifying_keys)
```
Comment (Pauan) [inline wasm/src/programs/execution.rs]: This should use `Object::keys` instead.

File: wasm/src/programs/execution.rs [hunk 5]
```diff
@@ -92,49 +100,84 @@ impl Deref for Execution {
...
+            .iter()
+            .filter_map(|entries| Array::try_from(entries).unwrap().get(0).as_string()) // Safe unwraps because `entries` returns arrays with string keys.
```
Comment (Pauan) [inline wasm/src/programs/execution.rs]: By using `Object::keys` this no longer needs to extract from an array.

File: wasm/src/programs/execution.rs [hunk 6]
```diff
@@ -92,49 +100,84 @@ impl Deref for Execution {
...
+        // Go through the imports and insert the verifying keys for each function.
+        for imported_program_id in &program_ids {
+            // Get the list of functions.
+            let vk_list = Array::try_from(
+                Reflect::get(&imported_verifying_keys, &imported_program_id.to_string().into())
+                    .map_err(|_| format!("Verifying key not found for imported program {}", imported_program_id))?,
+            )
+            .map_err(|_| format!("Verifying key not found for imported program {}", imported_program_id))?;
+            // Get the verifying key for each function.
+            for i in 0..vk_list.length() {
```
Comment (Pauan) [inline wasm/src/programs/execution.rs]: This should use `vk_list.iter()`

**Review by Pauan — DISMISSED** [review]
A couple minor things to fix.

**Comment by iamalwaysuncomfortable** [comment]
@alexpitsikoulis can you resolve the conflicts in the files?

File: sdk/src/program-manager.ts (hunk 2 above)
Comment (iamalwaysuncomfortable) [reply sdk/src/program-manager.ts:1986]: We do sorely need a better abstraction for this, but this is all the time we can spare for this at the moment.

Comment (Pauan) [reply sdk/src/program-manager.ts:1986]: Yeah, it's something I would like to work on in a separate PR.
