### PR TITLE
[Fix] Replace .unwrap() panics with descriptive errors in ExecutionRequest (#1220)

### LINKED ISSUE #1220: [Bug] Certain errors aren't surfaced
## 🐛 Bug Report

When there's a bug in WASM or I fetch a non-existent method I get inscrutible errors:

```
     RuntimeError: unreachable
      at wasm://wasm/048d6cee:wasm-function[6953]:0x8d8ed7
      at wasm://wasm/048d6cee:wasm-function[2834]:0x7b38a6
      at wasm://wasm/048d6cee:wasm-function[5739]:0x8bee53
      at wasm://wasm/048d6cee:wasm-function[6582]:0x8d6995
      at wasm://wasm/048d6cee:wasm-function[6560]:0x8d65dd
      at wasm://wasm/048d6cee:wasm-function[6247]:0x8d0083
      at wasm://wasm/048d6cee:wasm-function[3035]:0x7d2567
      at wasm://wasm/048d6cee:wasm-function[436]:0x3fe140
      at ExecutionRequest.fromString (file:///Users/victorsintnicolaas/programs/sdk/wasm/dist/mainnet/index.js:2694:18)
      at Context.<anonymous> (file:///Users/victorsintnicolaas/programs/sdk/sdk/tmp/mainnet/tests/program-manager.test.js:385:55)
```

To reproduce: 
- commit 6d5dd974 (HEAD -> rr/add-ts-support-code
- run the test "Program Manager public message signing"

### PR DESCRIPTION
**Pull request by marshacb**
## Motivation

WASM panics in `ExecutionRequest` methods surface as inscrutable `RuntimeError: unreachable` errors with no context (see #1220). The root cause: several methods in `request.rs` used `.unwrap()` on user input parsing, which panics on invalid input instead of returning a descriptive error.

This PR replaces all `.unwrap()` calls on user input in `ExecutionRequest` with proper `Result` error propagation:

- **`sign()`**: Input and input type parsing now return indexed, contextual errors (e.g., `"Invalid input 2 'foo': Failed to parse string..."`)
- **`verify()`**: Same treatment for input type parsing; return type changed from `bool` to `Result<bool, String>`
- **`compute_input_ids_with_record_view_keys()`**: `.pop().unwrap()` on record view keys and gammas replaced with `.ok_or_else()` descriptive messages

## Test Plan

- 3 new tests in `wasm.test.ts` verify that `ExecutionRequest` methods reject invalid inputs:
  - Structurally invalid request JSON
  - Completely invalid string input
  - `sign()` with invalid inputs — asserts error contains `"Invalid input"` from the Rust error path
- Full regression: existing WASM test suite passes with no new failures

```bash
yarn build:all
cd sdk && yarn test
```

Closes #1220

---

> [!NOTE]
> **Medium Risk**
> Medium risk because the WASM API for `ExecutionRequest.verify` changes from `bool` to `Result<bool, String>` and error paths now return early instead of panicking, which may require downstream caller updates.
> 
> **Overview**
> **WASM `ExecutionRequest` now returns descriptive errors instead of panicking** on invalid user-provided inputs.
> 
> `ExecutionRequest.sign` and `ExecutionRequest.verify` replace several `.unwrap()`s with indexed parsing/typing validation that returns `Result<_, String>` messages (and `verify`’s return type changes from `bool` to `Result<bool, String>`). Record-input ID computation also replaces `.pop().unwrap()` on record view keys/gammas with explicit “insufficient …” errors.
> 
> Adds SDK WASM tests asserting invalid request strings/JSON and invalid `sign()` inputs throw non-`WebAssembly.RuntimeError` exceptions and include the new Rust-side error text.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 5ed20ca9a189f9202c0e43f53c49312877c74c8f. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by iamalwaysuncomfortable — APPROVED** [review]

File: wasm/src/programs/request.rs [hunk 1]
```diff
@@ -538,14 +546,18 @@ impl ExecutionRequest {
...
-    pub fn verify(&self, input_types: Array, is_root: bool, program_checksum: Option<Field>) -> bool {
+    pub fn verify(&self, input_types: Array, is_root: bool, program_checksum: Option<Field>) -> Result<bool, String> {
         let input_types = input_types
             .iter()
-            .map(|input_type| ValueTypeNative::from_str(&input_type.as_string().unwrap()).unwrap())
-            .collect::<Vec<ValueTypeNative>>();
+            .enumerate()
+            .map(|(i, input_type)| {
+                let s = input_type.as_string().ok_or_else(|| format!("Input type {i} is not a string"))?;
+                ValueTypeNative::from_str(&s).map_err(|e| format!("Invalid input type {i} '{s}': {e}"))
```
Comment (iamalwaysuncomfortable) [inline wasm/src/programs/request.rs]:
```suggestion
                ValueTypeNative::from_str(&s).map_err(|e| format!("Failed to deserialize input {i} as input type '{s}' - please check the input at position {i} and try again: {e}"))
```

**Review by iamalwaysuncomfortable — COMMENTED** [review]
One small comment about the wording, but otherwise good to merge.

File: wasm/src/programs/request.rs (hunk 1 above)
Comment (iamalwaysuncomfortable) [reply wasm/src/programs/request.rs]: Basically apply this comment style for the `from_str` errors.

**Comment by vicsn** [comment]
Amazing!
