### PR TITLE
Changing JSON parsing to use bigint for all integers

### LINKED ISSUE #892: [Bug] Block data parsing loses precision and typing of bigInts
## 🐛 Bug Report

Using `response.json()` as a parser for results fetched from Aleo nodes removes precision from bigInts and transforms them into strings (leading to users needing to handle casting and handling them correctly).

## Steps to Reproduce

get a block containing a solution generated by a prover i.e block 4844 on testnet-beta, and check the values returned in the `solutions` part of the block, the result is that the `counter` element in the `partial_solutions` has lost the last 4 digits in precision and is now unexpectedly a string.

#### Code snippet to reproduce

```
import { AleoNetworkClient } from "sdk"
const networkClient = new AleoNetworkClient(ALEO_NODE_ENDPOINT)

const block = await networkClient.getBlock(4844)
```
Check the results of the blocks and verify wrong types: `counter: "4175780142384957400"` but it should be `counter: 4175780142384957663` (as a bigInt)

#### Stack trace & error message

no error message to be shown

## Expected Behavior

Expected behaviour is for the blocks to be returned with the right precision and having the correct typing such as bigInt allowing clients using the SDK.

## Your Environment

- node 20 alpine

### PR DESCRIPTION
**Pull request by Pauan**
Fixes #892.

This is an alternate solution to #901

This parses all integers as a BigInt. We might want to be more selective, such as only parsing certain keys as BigInt.

### CODE REVIEW

File: sdk/src/network-client.ts [hunk 1]
```diff
@@ -390,9 +392,9 @@ class AleoNetworkClient {
    * @example
    * const latestHeight = networkClient.getLatestHeight();
    */
-  async getLatestHeight(): Promise<number | Error> {
+  async getLatestHeight(): Promise<bigint | Error> {
```
Comment (iamalwaysuncomfortable) [inline sdk/src/network-client.ts]: Block height should likely stay `number` in return type because block height is a u32 (and thus within the range of `number`) and several methods take block height as a `number` type which would lead to a frustrating explicit cast for end users. 

Even though with `ParseJson` we'd get it back as a big int, it'll always be a safe conversion to `number`, so we should probably do that directly in this method. 

Otherwise treating all numbers in the block JSON as BigInt is a safe approach as there are a ton of numbers represented as `u64` (and even the stray `u128` here and there) in rust.

Comment (Pauan) [reply sdk/src/network-client.ts]: Yeah that's reasonable, I made that change.

**Review by jaketarnow — APPROVED** [review]
LGTM
